// examples/vue-sfc/src/list.vue
<template>
  <div id="root">
     <ul>
        <list-item v-for="item, index in items" />
      </ul>
  </div>

</template>
<script>
import ListItem from './list-item.vue'
export default {
   name: 'list',
   props: {
      items: Array
   },
   // functional: true,
   components: {
     ListItem
   }
}
</script>

// examples/react/src/List.js
import React from 'react'

const ListItem = () => {
  return <li>hi</li>
}

const ListItems = props => {
  return (
    <ul>
      {props.items.map((_, index) =>
        <ListItem key={index}/>
      )}
    </ul>
  )
}

const List = props => {
  return (
    <div>
      <ListItems {...props}/>
    </div>
  )
}

export default List
